language: java

os: linux

services:
  - docker
  
env:
  global:
    - HXE_VERSION=2.00.036.00.20190223.1
    - PASSWORD_FILE_CONTENT="{\"master_password\" : \"L1qu1base_test\"}"

before_script:
  - mkdir $TRAVIS_BUILD_DIR/HXE
  - chmod -R 777 $TRAVIS_BUILD_DIR/HXE
  - echo $PASSWORD_FILE_CONTENT > $TRAVIS_BUILD_DIR/HXE/password.json
  - chmod 777 $TRAVIS_BUILD_DIR/HXE/password.json
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull store/saplabs/hanaexpress:$HXE_VERSION
  - docker run -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v $TRAVIS_BUILD_DIR/HXE:/hana/mounts --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000 60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI store/saplabs/hanaexpress:$HXE_VERSION --passwords-url file:///hana/mounts/passwords.json --agree-to-sap-license
  - docker ps -a
  - docker exec -d HXETravisCI bash -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"

addons:
  hosts:
  - hxehost