language: java

os: linux

services:
  - docker

before_script:
- sh -c "mkdir -p /data/HXE"
- sh -c "chown 12000:79 /data/HXE"
- sh -c "echo '{\"master_password\" : \"L1qu1base_test\"}' > /data/HXE/password.json"
- sh -c "chmod 600 /data/HXE/password.json"
- sh -c "chown 12000:79 /data/HXE/password.json"
- docker pull store/saplabs/hanaexpress:2.00.036.00.20190223.1
- docker run -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/HXE:/hana/mounts --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000 60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI store/saplabs/hanaexpress:2.00.036.00.20190223.1 --passwords-url file:///hana/mounts/passwords.json --agree-to-sap-license
- docker ps -a
- docker exec -d HXETravisCI bash -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"

addons:
  hosts:
  - hxehost